config/routes.rb
GetYourBook::Application.routes.draw do
  resources :rents, :only => [:index, :create, :update]

  devise_for :users

  resources :books, :only => [:index, :show]

  root :to => "books#index"

end

app/models/author.rb
class Author < ActiveRecord::Base
  attr_accessible :name
end

app/models/book.rb
class Book < ActiveRecord::Base
  # attribute accessible
  attr_accessible :author_id, :image, :is_available, :title

  # relationships
  belongs_to :author
  has_many :rents
  has_many :students, :through => :rents

  # scopes
  scope :latest_rent, lambda { order("title ASC") }
  scope :order_by_title, lambda { order("title ASC") }
  scope :by_title, lambda { |title| where("title LIKE ?", "%#{title}%") }
  scope :available, lambda { |is_available| where("is_available = ?", !is_available.to_i.zero?) }
  scope :by_author_id, lambda { |author_id| where("author_id = ?", author_id) }
end

app/models/rent.rb
class Rent < ActiveRecord::Base
  attr_accessible :book_id, :delivered_at, :status, :student_id, 
                  :user_id, :withdrawn_at, :delivery_expected_at
  # callbacks
  before_create :set_delivery_expected_at, :set_status

  # relationships
  belongs_to :book
  belongs_to :student
  belongs_to :user

  def save_book
    self.book.is_available = false
    self.book.save
  end

  protected

  def set_delivery_expected_at
    self.delivery_expected_at = Time.now + 7.days
  end

  def set_status
    self.status = :rented
  end
end

app/models/student.rb
class Student < ActiveRecord::Base
  attr_accessible :name, :registration

  # relationship
  has_many :rents
  has_many :books, :through => :rents
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, #:registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :registration, :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :authenticate_user!
  before_filter :preloader

  def preloader
    @authors = Author.all
  end
end

app/controllers/books_controller.rb
# encoding: utf-8
class BooksController < ApplicationController
  def index
    @books = Book.order_by_title
    @books = @books.by_title params[:title] if params[:title].present?
    @books = @books.by_author_id params[:author_id] if params[:author_id].present?
    @books = @books.available params[:is_available] if params[:is_available].present?
  end
  
  def show
    @book = Book.find(params[:id])
    @current_rent = @book.rents.last
    @students = Student.all
    @rent = Rent.new
  end
end

app/controllers/rents_controller.rb
# encoding: utf-8
class RentsController < ApplicationController
  def index
    @rents = Rent.order('created_at DESC')
  end

  def create
    rent = Rent.new(params[:rent])
    rent.user_id = current_user.id

    begin
      rent.save
      rent.save_book

      flash[:success] = "The book was marked with rented"
      redirect_to rents_path
    rescue Exception => e
      flash[:error] = "An error occurred while trying to rent the book, try again. <br /> #{e.message}"
      redirect_to book_path @rent.book
    end
  end

  def edit
    @rent = Rent.find(params[:id])
  end

  def update
    rent = Rent.find(params[:id])
    rent.status = :delivered
    rent.delivered_at = Date.today
    
    begin
      rent.save
      rent.book.is_available = true
      rent.book.save
      flash[:success] = "The book was marked with received"
      redirect_to rents_path
    rescue Exception => e
      flash[:error] = "An error occurred while trying to rent the book, try again. <br /> #{e.message}"
      redirect_to book_path @rent.book
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_message
    messages = ""
    [:success, :info, :warning, :error].each {|type|
      if flash[type]
        messages += render "shared/alert", type: type, message: flash[type]
      end
    }
    messages
  end
end

app/helpers/books_helper.rb
module BooksHelper
  def get_status(book)
    label = book.is_available ? "This book is available." : "Unavailable, Check availabity."
    type = book.is_available ? "success" : "warning"
    content_tag :span, label, :class => "badge badge-#{type}"
  end

  def available_link_to(book)
    if book.is_available
      link_to "Catch it", book_path(book), :class => "btn btn-large btn-success"
    else
      link_to "Check availability", book_path(book), :class => "btn btn-large btn-warning"
    end
  end
end

app/helpers/rents_helper.rb
module RentsHelper
  def statuses(rent)
    type = rent.status != "delivered" ? "warning" : "success"
    content_tag :span, rent.status, :class => "label label-#{type}"
  end
end

app/views/books/_search.html.erb
<%= form_tag root_path, :method => :get, :class => "input-append" do %>
  <div class="input-prepend">
    <%= search_field_tag :title, params[:title], :class => "span3", :placeholder => "search by title" %>
  </div>
  <div class="input-append input-prepend">
    <%= select_tag :author_id, options_for_select([["All authors", ""]]) + options_from_collection_for_select(@authors, "id", "name", :selected=> params[:author_id]), :class => "span3" %>
    
    <%= select_tag :is_available, options_for_select([["All availability", nil], ["Available", 1], ["Unavailable", 0]], :selected=> params[:is_available]), :class => "span3" %>
    
    <%= submit_tag "Go", :class => "btn btn-info" %>
  </div>      
<% end %>

app/views/books/index.html.erb
<div class="row">
  <div class="span3">
    <%= render "shared/sidebar" %>
  </div>
  <div class="span9">
    <div id="books">
      <p><%= render "search" %></p>
      <% if @books.present? %>
        <div class="row">
          <% @books.each do |book| %>
            <div class="span3">
              <figure>
                <figcaption>
                  <h3><%= book.title %></h3>
                  <p class="author"><%= book.author.name %></p>
                </figcaption>
                <%= image_tag book.image %>
              </figure>
              <div class="actions">
                <%= available_link_to book %>
              </div>
            </div>
          <% end %>
        </div>
      <% else %>
        <p class="alert"><b>Atention!</b> <br /> Sorry, no book was found. <%= link_to "See all", root_path %>.</p>
      <% end %>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="row">
  <div class="span3">
    <%= render "shared/sidebar" %>
  </div>
  <div class="span9">
    <p><%= render "search" %></p>
    <div id="book" class="row">
      <div class="span3">
        <figure>
          <%= image_tag @book.image %>
        </figure>
      </div>
      <div class="span6 details">
        <h2><%= @book.title %></h2>
        <p class="author"><%= @book.author.name %> <%= get_status @book %></p>

        <div id="form-rent">
          <% if @book.is_available %>
            <%= semantic_form_for @rent do |f| %>
              <%= f.input :book_id, :as => :hidden, :input_html => { :value => @book.id } %>
              <label>Choose a students</label>
              <div class="input-append">
                <%= f.input :student_id, :as => :select, :label => false, :collection => @students %>

                <%= f.button "Catch it", :class => "btn btn-success" %>
              </div>
            <% end %>
            <%= link_to "back to books", books_path, :class => "btn btn-mini" %>
          <% else %>
            <div class="alert">The book was leased by <b><%= @current_rent.student.name %></b> and is expected to 
            be delivered on <b><%= @current_rent.delivery_expected_at.strftime("%B %d, %Y") %></b>. <br>
            <b>Employee who leased the book</b>: <i><%= @current_rent.user.name %></i>.</div>

              <%= semantic_form_for @current_rent do |f| %>
                <%= f.button "receive book", :class => "btn btn-warning" %>
                <%= link_to "back to books", books_path, :class => "btn btn-mini" %>
              <% end %>
          <% end %>
            
        </div>
      </div>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<div class="row">
  <div class="span3"><h1>Books</h1></div>
  <div class="span9">
    <br>
    <%= render "books/search" %>
  </div>
</div>

<div id="books" class="row">
  <% if @books.present? %>
    <% @books.each do |book| %>
    <div class="span3">
      <figure>
        <figcaption>
          <h3><%= book.title %></h3>
          <p class="author"><%= book.author.name %></p>
        </figcaption>
        <%= image_tag book.image %> 
      </figure>
      <div class="actions">
        <% if book.is_available %>
          <%= link_to "Catch it", book_path(book), :class => "btn btn-large btn-success" %>
        <% else %>
          <%= link_to "Check availability", book_path(book), :class => "btn btn-large btn-warning" %>
        <% end %>
      </div>
    </div>
    <% end %>
  <% else %>
    <p class="alert"><b>Atention!</b> <br /> Sorry, no book was found. <%= link_to "See all", root_path %>.</p>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html><head>

<title>Get Your Book</title>
<%= stylesheet_link_tag "application", :media => "all" %>
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<%= csrf_meta_tags %>

<!--[if lt IE 8]><%= stylesheet_link_tag "application-ie", media: "all" %><![endif]-->

<%= favicon_link_tag %>

</head><body>

<%= flash_message.html_safe %>

<div class="container">
  <%= yield %>
  <br clear="all" />
</div>

<footer class="navbar navbar-inverse navbar-fixed-bottom">
  <div class="navbar-inner">
    <div class="container">
      <a class="brand" href="<%= root_path %>"><i class="icon-book"></i> Get Your Book</a>
      <ul class="nav pull-right">
        <li><%= link_to image_tag("http://images.wfsneto.com.br/logo.png"), "http://wfsneto.com.br", :target => "_blank" %></li>
      </ul>
    </div>
  </div>
</footer>

<%= javascript_include_tag "application" %>

</body></html>

app/views/rents/index.html.erb
<div class="row">
  <div class="span3">
    <%= render "shared/sidebar" %>
  </div>
  <div class="span9">
    <p><%= render "books/search" %></p>
    <% if @rents.present? %>
      <div id="rents">
        <table class="table table-bordered table-hover"><thead>
          <tr>
            <th>Book</th>
            <th>Rented by</th>
            <th>Status</th>
            <th>Created at</th>
            <th>Expected at</th>
            <th>Delivered at</th>
            <th>&nbsp;</th>
          </tr>
        </thead><tbody>
          <% @rents.each do |rent| %>
            <tr>
              <td><%= rent.book.title %></td>
              <td><%= rent.student.name %></td>
              <td><%= statuses rent %></td>
              <td class="center"><%= time_ago_in_words rent.created_at %></td>
              <td class="center"><%= rent.delivery_expected_at.strftime("%B %d") %></td>
              <td class="center"><%= rent.delivered_at.present? ? rent.delivered_at.strftime("%B %d") : "not yet" %></td>
              <td class="center">
                <%= link_to '', rent.book, :class => 'icon-eye-open' %>
              </td>
            </tr>
          <% end %>
        </tbody></table>
      </div>
    <% else %>
      <p class="alert"><b>Atention!</b> record not found.</p>
    <% end %>
  </div>
</div>

app/views/shared/_alert.html.erb
<div class="container" style="margin-top:10px">
  <div class="alert alert-<%= type %>">
    <span class="close" data-dismiss="alert">×</span>
    <b><%= type.capitalize %>!</b> <br /> <%= message.html_safe %>
  </div>
</div>

app/views/shared/_sidebar.html.erb
<div class="affix">
  <h1><i class="icon-book"></i> <%= params[:controller].capitalize %></h1>
  <ul class="nav nav-list">
    <li class="<%= 'active' if params[:controller] == "books" %>"><%= link_to 'Books', books_path %></li>
    <li class="<%= 'active' if params[:controller] == "rents" %>"><%= link_to 'Rents', rents_path %></li>
    <li><%= link_to 'Logout', destroy_user_session_path, :method => :delete %></li>
  </ul>
</div>